CREATE TABLE `ALBUM`
(
  `ID`    INT PRIMARY KEY AUTO_INCREMENT,
  `NAME`  VARCHAR(100) NOT NULL,
  `IMAGE` LONGBLOB
);

CREATE TABLE `WORSHIP`
(
  `ID`    INT PRIMARY KEY AUTO_INCREMENT,
  `NAME`  VARCHAR(100) NOT NULL,
  `IMAGE` LONGBLOB
);

CREATE TABLE `SONG`
(
  `ID`       INT PRIMARY KEY AUTO_INCREMENT,
  `NAME`     VARCHAR(100) NOT NULL,
  `FILE`     LONGBLOB     NOT NULL,
  `ORDER`    INT          NOT NULL,
  `ALBUM_ID` INT          NOT NULL
);

CREATE TABLE `MOMENT`
(
  `ID`         INT PRIMARY KEY AUTO_INCREMENT,
  `NAME`       VARCHAR(100) NOT NULL,
  `SUBGROUP`   INT,
  `ORDER`      INT          NOT NULL,
  `ALBUM_ID`   INT          NOT NULL,
  `WORSHIP_ID` INT          NOT NULL
);

ALTER TABLE SONG
  ADD CONSTRAINT FK_ALBUM_ID
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM (ID);

ALTER TABLE MOMENT
  ADD CONSTRAINT FK_MOMENT_ALBUM_ID
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM (ID);

ALTER TABLE MOMENT
  ADD CONSTRAINT FK_WORSHIP_ID
    FOREIGN KEY (WORSHIP_ID) REFERENCES WORSHIP (ID);
