CREATE TABLE `ALBUM`
(
  `ID`    INT PRIMARY KEY AUTO_INCREMENT,
  `NAME`  VARCHAR(100) NOT NULL,
  `IMAGE` VARCHAR(100)
);

CREATE TABLE `WORSHIP`
(
  `ID`    INT PRIMARY KEY AUTO_INCREMENT,
  `NAME`  VARCHAR(100) NOT NULL,
  `IMAGE` VARCHAR(100)
);

CREATE TABLE `SONG`
(
  `ID`       INT PRIMARY KEY AUTO_INCREMENT,
  `NAME`     VARCHAR(100) NOT NULL,
  `FILE`     VARCHAR(100) NOT NULL,
  `ORDER`    INT          NOT NULL,
  `ALBUM_ID` INT          NOT NULL
);

CREATE TABLE `MOMENT`
(
  `ID`             INT PRIMARY KEY AUTO_INCREMENT,
  `NAME`           VARCHAR(100) NOT NULL,
  `SUBGROUP_NAME`  VARCHAR(100),
  `ORDER`          INT          NOT NULL,
  `SONG_ID`       INT          NOT NULL,
  `WORSHIP_ID`     INT          NOT NULL
);

ALTER TABLE SONG
  ADD CONSTRAINT FK_ALBUM_ID
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM (ID);

ALTER TABLE MOMENT
  ADD CONSTRAINT FK_MOMENT_SONG_ID
    FOREIGN KEY (SONG_ID) REFERENCES SONG (ID);

ALTER TABLE MOMENT
  ADD CONSTRAINT FK_WORSHIP_ID
    FOREIGN KEY (WORSHIP_ID) REFERENCES WORSHIP (ID);
